# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 16:53
from __future__ import unicode_literals

from django.db import migrations
import json_schema.fields


class Migration(migrations.Migration):
    dependencies = [
        ('json_schema_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonschemamodel',
            name='test_field',
            field=json_schema.fields.JSONSchemaField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
