# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('json_schema_app', '0002_auto_20171212_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonschemamodel',
            old_name='test_field',
            new_name='parent',
        ),
    ]
