# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('json_schema_app', '0003_auto_20171214_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonschemamodel',
            name='simple_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsonschemamodel',
            name='simple_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
