# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models

import json_schema.fields


class Migration(migrations.Migration):
    dependencies = [
        ('json_schema_app', '0004_auto_20171219_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSchemaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_json', json_schema.fields.JSONSchemaField(blank=True)),
            ],
        ),
    ]
