# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 16:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('json_schema_app', '0005_noschemamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonschemamodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=256, null=True),
        ),
    ]
