# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('json_schema_app', '0007_auto_20171219_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonschemamodel',
            name='description',
        ),
    ]
