# Generated by Django 2.1.5 on 2019-01-14 12:54

from django.db import migrations, models
import json_schema.fields


class Migration(migrations.Migration):

    dependencies = [
        ('json_schema_app', '0008_remove_jsonschemamodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSchemaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', json_schema.fields.JSONSchemaField()),
            ],
        ),
    ]
