# Generated by Django 2.1.5 on 2019-01-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_schema_app', '0010_noschemamodel_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileSchemaModel',
        ),
        migrations.RemoveField(
            model_name='noschemamodel',
            name='file',
        ),
    ]
