# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 14:31
from __future__ import unicode_literals

import json_schema.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONSchemaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', json_schema.fields.JSONWidgetField(blank=True, default={}, null=True)),
            ],
        ),
    ]
